apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: cluster-operate
spec:
  admission: true
  background: false
  rules:
    - generate:
        apiVersion: provisioning.cattle.io/v1
        data:
          metadata:
            annotations:
              "gorizond-user.{{ request.userInfo.username }}.admin": admin
        kind: Cluster
        name: "{{request.object.metadata.name}}"
        namespace: "{{request.object.metadata.namespace}}"
      name: create-cluster
      match:
        any:
          - resources:
              kinds:
                - provisioning.gorizond.io/v1alpha1/Cluster
              operations:
                - CREATE
    - mutate:
        targets:
         - apiVersion: provisioning.cattle.io/v1
           kind: Cluster
           name: "{{request.object.metadata.name}}"
           namespace: "{{request.object.metadata.namespace}}"
        patchStrategicMerge:
          metadata:
            labels:
              cleanup.kyverno.io/ttl: '1m'
      name: delete-cluster
      match:
        any:
          - resources:
              kinds:
                - provisioning.gorizond.io/v1alpha1/Cluster
              operations:
                - DELETE