apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: gorizond-user-creator-binding
spec:
  admission: true
  background: true
  rules:
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          clusterName: "{{ request.object.metadata.name }}"
          roleTemplateName: cluster-owner
          userName: '{{ request.object.metadata.annotations."gorizond-user-creator" }}'
        kind: ClusterRoleTemplateBinding
        namespace: "{{ request.object.metadata.name }}"
        name: "crb-admin-{{ request.object.metadata.uid }}"
      name: create-cluster
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/Cluster
              operations:
                - CREATE
    - name: update-k8s-cluster-status
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/Cluster
              operations:
                - UPDATE
      preconditions:
        all:
          - key: '{{request.object.metadata.name }}'
            operator: NotEquals
            value: 'local'
      mutate:
        targets:
         - apiVersion: provisioning.gorizond.io/v1alpha1
           kind: Cluster
           name: "{{request.object.spec.displayName }}"
           namespace: "{{request.object.spec.fleetWorkspaceName }}"
        patchesJson6902: |-
          - op: add
            path: /status/time
            value: "{{ time_now_utc() }}"