apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: gorizond-user-creator-binding
spec:
  admission: true
  background: true
  rules:
    - generate:
        apiVersion: rbac.authorization.k8s.io/v1
        data:
          clusterName: "{{ request.object.status.clusterName }}"
          roleTemplateName: cluster-owner
          userName: '{{ request.object.metadata.annotations."gorizond-user-creator" }}'
        kind: ClusterRoleTemplateBinding
        namespace: "{{ request.object.status.clusterName }}"
        name: "crb-admin-{{ request.object.metadata.uid }}"
      name: create-cluster
      match:
        any:
          - resources:
              kinds:
                - provisioning.cattle.io/v1/Cluster
              operations:
                - CREATE