apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: gorizond-user-creator-binding
spec:
  admission: true
  background: false
  rules:
    - generate:
        apiVersion: rbac.authorization.k8s.io/v1
        data:
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: "{{ request.object.status.clusterName }}-clusterowner"
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: '{{ request.object.metadata.annotations."gorizond-user-creator" }}'
        kind: ClusterRoleBinding
        name: "crb-admin-{{ request.object.metadata.uid }}"
      name: create-cluster
      match:
        any:
          - resources:
              kinds:
                - provisioning.cattle.io/v1/Cluster
              operations:
                - CREATE