apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-create-user-fleetworkspace
spec:
  admission: true
  background: true
  rules:
    - name: generate-fleetworkspace
      match:
        any:
        - resources:
            kinds:
              - management.cattle.io/v3/User
      preconditions:
        any:
        - key: "{{request.operation}}"
          operator: Equals
          value: "CREATE"
      generate:
        kind: FleetWorkspace
        apiVersion: management.cattle.io/v3
        name: "{{request.object.username}}-workspace"
        synchronize: true
        data:
          metadata:
            name: "{{request.object.username}}-workspace"
          spec:
            displayName: "Workspace for {{request.object.username}}"