apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-create-user-globalrole-bindig
spec:
  admission: true
  background: true
  rules:
    - name: generate-globalrole-bindig
      match:
        any:
        - resources:
            kinds:
              - management.cattle.io/v3/GlobalRole
      generate:
        kind: GlobalRoleBinding
        apiVersion: management.cattle.io/v3
        name: "gorizond-{{request.object.metadata.name}}-{{request.object.metadata.annotations.\"gorizond-user-create\"}}"
        data:
          metadata:
            name: "gorizond-{{request.object.metadata.name}}-{{request.object.metadata.annotations.\"gorizond-user-create\"}}"
            annotations:
              gorizond-user-create: "{{request.object.metadata.annotations.\"gorizond-user-create\"}}"
          globalRoleName: "{{request.object.metadata.name}}"
          userName: "{{request.object.metadata.annotations.\"gorizond-user-create\"}}"
