apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-create-user-fleetworkspace
spec:
  admission: true
  background: true
  rules:
    - name: generate-fleetworkspace
      match:
        any:
        - resources:
            kinds:
              - management.cattle.io/v3/User
      generate:
        kind: FleetWorkspace
        apiVersion: management.cattle.io/v3
        name: "{{request.object.username}}-workspace"
        data:
          metadata:
            name: "{{request.object.username}}-workspace"
            annotations:
              gorizond-user-create: "{{request.object.metadata.name}}"
          spec:
            displayName: "Workspace for {{request.object.username}}"