apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: generate-globalrolebindings-from-annotations
spec:
  admission: true
  background: true
  rules:
    - generate:
        foreach:
          - apiVersion: management.cattle.io/v3
            context:
              - name: user
                variable:
                  jmesPath: element | split(@, '.') | @[1]
              - name: role
                variable:
                  jmesPath: element | split(@, '.') | @[2]
            data:
              globalRoleName: gorizond-{{ role }}-{{ request.object.metadata.name }}
              metadata:
                annotations:
                  gorizond-user.{{ user }}.{{ role }}: "{{ role }}"
                labels:
                  fleet: "{{ request.object.metadata.name }}"
              userName: "{{ user }}"
            kind: GlobalRoleBinding
            list: keys(request.object.metadata.annotations) | [?starts_with(@, 'gorizond-user.')]
            name: gorizond-{{ role }}-{{ user }}-{{ request.object.metadata.name }}
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/FleetWorkspace
      name: sync-gorizond-bindings
      skipBackgroundRequests: true
    - context:
        - apiCall:
            method: GET
            urlPath: >-
              /apis/management.cattle.io/v3/globalrolebindings?labelSelector=fleet%3D{{
              request.object.metadata.name }}
          name: globalBindings
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/FleetWorkspace
              operations:
                - CREATE
      mutate:
        foreach:
          - list: globalBindings
            patchStrategicMerge:
              metadata:
                annotations:
                  last-check: "{{ time_now_utc() }}"
                labels:
                  binding: check
        targets:
          - apiVersion: management.cattle.io/v3
            kind: GlobalRoleBinding
            selector:
              matchLabels:
                fleet: "{{ request.object.metadata.name }}"
      name: check-gorizond-bindings
