apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-globalrolebindings-from-annotations
spec:
  admission: true
  background: true
  rules:
    - generate:
        foreach:
          - apiVersion: management.cattle.io/v3
            context:
              - name: user
                variable:
                  jmesPath: element | split(@, '.') | @[1]
              - name: role
                variable:
                  jmesPath: element | split(@, '.') | @[2]
            data:
              metadata:
                labels:
                  fleet: '{{ request.object.metadata.name }}'
                annotations:
                  'gorizond-user.{{ user }}.{{ role }}': '{{ role }}'
              globalRoleName: 'gorizond-{{ role }}-{{ request.object.metadata.name }}'
              userName: '{{ user }}'
            kind: GlobalRoleBinding
            list: keys(request.object.metadata.annotations) | [?starts_with(@, 'gorizond-user.')]
            name: gorizond-{{ role }}-{{ user }}-{{ request.object.metadata.name }}
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/FleetWorkspace
      name: sync-gorizond-bindings
    - name: mark-globalrolebinding-as-canremove-if-annotation-missing
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/FleetWorkspace
      context:
        - name: globalBindings
          apiCall:
            urlPath: "/apis/management.cattle.io/v3/globalrolebindings"
            jmesPath: "items[?metadata.labels.fleet=='{{ request.object.metadata.name }}']"
        - name: annotationsFW
          variable:
            jmesPath: keys(request.object.metadata.annotations)
      mutate:
        targets:
          - apiVersion: "management.cattle.io/v3"
            kind: GlobalRoleBinding
            selector:
              matchLabels:
                fleet: '{{ request.object.metadata.name }}'
        foreach:
          - list: "globalBindings"
            preconditions:
              all:
                - key: "{{ keys(element.metadata.annotations) }}"
                  operator: AnyNotIn
                  value: "{{ annotationsFW }}"
            patchStrategicMerge:
              metadata:
                labels:
                  canremove: 'true'