apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-fleetworkspace-on-user
spec:
  admission: true
  background: false
  rules:
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          metadata:
            annotations:
              gorizond-user.{{request.object.metadata.name}}.admin: admin
          spec: {}
        kind: FleetWorkspace
        name: '{{request.object.username}}-workspace'
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/User
      name: generate-fleetworkspace
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          displayName: GitOps for {{request.object.username}} admin
          namespacedRules:
            '{{request.object.username}}-workspace':
              - apiGroups:
                  - fleet.cattle.io
                resources:
                  - gitrepos
                  - bundles
                  - clusterregistrationtokens
                  - gitreporestrictions
                  - clusters
                  - clustergroups
                verbs:
                  - '*'
          rules:
            - apiGroups:
                - management.cattle.io
              resourceNames:
                - '{{request.object.username}}-workspace'
              resources:
                - fleetworkspaces
              verbs:
                - '*'
        kind: GlobalRole
        name: gorizond-admin-{{request.object.username}}-workspace
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/User
      name: generate-admin-role
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          displayName: GitOps for {{request.object.username}} editor
          namespacedRules:
            '{{request.object.username}}-workspace':
              - apiGroups:
                  - fleet.cattle.io
                resources:
                  - gitrepos
                  - bundles
                  - clusterregistrationtokens
                  - gitreporestrictions
                  - clusters
                  - clustergroups
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - patch
                  - delete
          rules:
            - apiGroups:
                - management.cattle.io
              resourceNames:
                - '{{request.object.username}}-workspace'
              resources:
                - fleetworkspaces
              verbs:
                - get
                - list
                - watch
                - update
                - patch
        kind: GlobalRole
        name: gorizond-editor-{{request.object.username}}-workspace
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/User
      name: generate-editor-role
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          displayName: GitOps for {{request.object.username}} view
          namespacedRules:
            '{{request.object.username}}-workspace':
              - apiGroups:
                  - fleet.cattle.io
                resources:
                  - gitrepos
                  - bundles
                  - clusterregistrationtokens
                  - gitreporestrictions
                  - clusters
                  - clustergroups
                verbs:
                  - get
                  - list
                  - watch
          rules:
            - apiGroups:
                - management.cattle.io
              resourceNames:
                - '{{request.object.username}}-workspace'
              resources:
                - fleetworkspaces
              verbs:
                - get
                - list
                - watch
        kind: GlobalRole
        name: gorizond-view-{{request.object.username}}-workspace
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/User
      name: generate-view-role
