apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-create-user-globalrole
spec:
  admission: true
  background: true
  rules:
    - name: generate-globalrole
      match:
        any:
        - resources:
            kinds:
              - management.cattle.io/v3/FleetWorkspace
      generate:
        kind: GlobalRole
        apiVersion: management.cattle.io/v3
        name: "fleet-workspace-{{request.object.username}}"
        synchronize: true
        data:
          metadata:
            name: "fleet-workspace-{{request.object.username}}"
          rules:
            - apiGroups: ["management.cattle.io"]
              resourceNames: ["{{request.object.username}}-workspace"]
              resources: ["fleetworkspaces"]
              verbs: ["*"]
          namespacedRules:
            "{{request.object.username}}-workspace":
              - apiGroups: ["fleet.cattle.io"]
                resources:
                  - gitrepos
                  - bundles
                  - clusterregistrationtokens
                  - gitreporestrictions
                  - clusters
                  - clustergroups
                verbs: ["*"]