apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-create-user-globalrole
spec:
  admission: true
  background: true
  rules:
    - name: generate-globalrole
      match:
        any:
        - resources:
            kinds:
              - management.cattle.io/v3/FleetWorkspace
      generate:
        kind: GlobalRole
        apiVersion: management.cattle.io/v3
        name: "fwgr-{{request.object.metadata.name}}"
        data:
          metadata:
            name: "fwgr-{{request.object.metadata.name}}"
            annotations:
              gorizond-user-create: "{{request.object.metadata.annotations.\"gorizond-user-create\"}}"
          rules:
            - apiGroups: ["management.cattle.io"]
              resourceNames: ["{{request.object.metadata.name}}"]
              resources: ["fleetworkspaces"]
              verbs: ["*"]
          namespacedRules:
            "{{request.object.metadata.name}}":
              - apiGroups: ["fleet.cattle.io"]
                resources:
                  - gitrepos
                  - bundles
                  - clusterregistrationtokens
                  - gitreporestrictions
                  - clusters
                  - clustergroups
                verbs: ["*"]