apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-create-fleetworkspace
spec:
  admission: true
  background: true
  rules:
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          metadata:
            name: '{{request.object.username}}-workspace'
          spec:
            displayName: Workspace for {{request.object.username}}
        kind: FleetWorkspace
        name: '{{request.object.username}}-workspace'
        synchronize: true
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/User
      name: generate-fleetworkspace
    - generate:
        apiVersion: management.cattle.io/v3
        kind: GlobalRole
        metadata:
          name: 'fleet-{{request.object.username}}-workspace'
        namespacedRules:
          '{{request.object.username}}-workspace':
            - apiGroups:
                - fleet.cattle.io
              resources:
                - gitrepos
                - bundles
                - clusterregistrationtokens
                - gitreporestrictions
                - clusters
                - clustergroups
              verbs:
                - '*'
        rules:
          - apiGroups:
              - management.cattle.io
            resourceNames:
              - '{{request.object.username}}-workspace'
            resources:
              - fleetworkspaces
            verbs:
              - '*'
        synchronize: true
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/User
      name: generate-globalrole