apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-cluster-role-binding
spec:
  admission: true
  background: true
  rules:
    - name: generate-globalrole-binding
      match:
        any:
        - resources:
            kinds:
              - management.cattle.io/v3/GlobalRole
      generate:
        kind: GlobalRoleBinding
        apiVersion: management.cattle.io/v3
        name: "gorizond-grb-{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            name: "gorizond-grb-{{request.object.metadata.name}}"
          userName: "{{request.object.metadata.name}}"
          globalRoleName: "fleet-workspace-{{request.object.username}}"
