apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gorizond-user-created-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: user-created-event
      eventSourceName: gorizond-user-events
      eventName: user-watcher
  template:
    serviceAccountName: gorizond-events-sa
  triggers:
    - template:
        k8s:
          operation: create
          parameters:
            - dest: userName
              src:
                dependencyName: user-created-event
          source:
            resource:
              apiVersion: management.cattle.io/v3
              kind: FleetWorkspace
              metadata:
                name: '{{ .Inputs.userName }}-workspace'
        name: create-fleet-workspace