defaultNamespace: argo-events

labels:
  argo: events

helm:
  release: argo-events
  repo: https://argoproj.github.io/argo-helm
  chart: argo-events
  values:
    controller:
      replicas: 3
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 128Mi
