apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: gorizond-cluster-events
spec:
  admission: true
  background: true
  rules:
    - generate:
        apiVersion: batch/v1
        data:
          spec:
            template:
              spec:
                containers:
                  - args:
                      - >-
                        kubectl patch -n "{{`{{ request.object.spec.fleetWorkspaceName }}`}}" cluster.provisioning.gorizond.io "{{`{{ request.object.spec.displayName }}`}}" --type=merge --subresource status -p '{"status": {"conditions": {{`{{ request.object.status.conditions }}`}}}}' || echo true
                    command:
                      - /bin/sh
                      - '-c'
                    image: bitnami/kubectl:latest
                    imagePullPolicy: IfNotPresent
                    name: kubectl
                restartPolicy: Never
                serviceAccount: kyverno-background-controller
                serviceAccountName: kyverno-background-controller
            ttlSecondsAfterFinished: 0
        kind: Job
        name: cluster-status-{{`{{ request.object.metadata.name }}`}}
        namespace: kyverno
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/Cluster
              operations:
                - UPDATE
      name: generate-cluster-status
      preconditions:
        all:
          - key: '{{`{{request.object.metadata.name }}`}}'
            operator: NotEquals
            value: local