apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: gorizond-cluster-events
spec:
  admission: true
  background: true
  rules:
    - generate:
        apiVersion: batch/v1
        data:
          spec:
            template:
              spec:
                containers:
                  - args:
                      - >-
                        kubectl patch -n "{{`{{ request.object.metadata.namespace }}`}}" cluster.provisioning.gorizond.io "{{`{{ request.object.metadata.labels.cluster }}`}}" --type=merge --subresource status -p '{"status": {"k3sToken": "{{`{{ request.object.data.token }}`}}"}}' || echo true
                    command:
                      - /bin/sh
                      - '-c'
                    image: bitnami/kubectl:latest
                    imagePullPolicy: IfNotPresent
                    name: kubectl
                restartPolicy: Never
                serviceAccount: kyverno-background-controller
                serviceAccountName: kyverno-background-controller
            ttlSecondsAfterFinished: 0
        kind: Job
        name: cluster-status-{{`{{ request.object.metadata.name }}`}}-k3s-token
        namespace: kyverno
      match:
        any:
          - resources:
              kinds:
                - v1/Secret
              selector:
                matchLabels:
                  k3s: token
              operations:
                - UPDATE
      name: generate-cluster-status-k3s-token
    - generate:
        apiVersion: batch/v1
        data:
          spec:
            template:
              spec:
                containers:
                  - args:
                      - >-
                        kubectl patch -n "{{`{{ request.object.metadata.namespace }}`}}" cluster.provisioning.gorizond.io "{{`{{ request.object.metadata.labels.cluster }}`}}" --type=merge --subresource status -p '{"status": {"headscaleToken": "{{`{{ request.object.data.token }}`}}"}}' || echo true
                    command:
                      - /bin/sh
                      - '-c'
                    image: bitnami/kubectl:latest
                    imagePullPolicy: IfNotPresent
                    name: kubectl
                restartPolicy: Never
                serviceAccount: kyverno-background-controller
                serviceAccountName: kyverno-background-controller
            ttlSecondsAfterFinished: 0
        kind: Job
        name: cluster-status-{{`{{ request.object.metadata.name }}`}}-headscale-token
        namespace: kyverno
      match:
        any:
          - resources:
              kinds:
                - v1/Secret
              selector:
                matchLabels:
                  headscale: token
              operations:
                - UPDATE
      name: generate-cluster-status-headscale-token