apiVersion: batch/v1
kind: Job
metadata:
  name: gorizond-create-truncate-db
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: create-truncate-database
          image: {{ $.Values.hs.database.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: HS_DB_USERNAME
              value: "{{ .Values.hs.database.username }}"
            - name: HS_DB_PASSWORD
              value: "{{ .Values.hs.database.password }}"
            - name: HS_DB_HOSTNAME
              value: "{{ .Values.hs.database.hostname }}"
            - name: HS_DB_PORT
              value: "{{ .Values.hs.database.port }}"
            - name: HS_DB_QUERY
              value: "{{ .Values.hs.database.query }}"
          command: ["sh", "-c"]
          args:
            - |
              {{ .Values.hs.database.connectionCli }} "CREATE DATABASE gorizond_truncate;"
              {{ .Values.hs.database.connectionCli }} "CREATE TABLE gorizond_truncate.table_to_delete (id TEXT PRIMARY KEY);"