apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: gorizond-user-creator-binding
spec:
  admission: true
  background: true
  rules:
    - generate:
        apiVersion: management.cattle.io/v3
        data:
          clusterName: "\{{ request.object.metadata.name }}"
          roleTemplateName: cluster-owner
          userName: '\{{ request.object.metadata.annotations."gorizond-user-creator" }}'
        kind: ClusterRoleTemplateBinding
        namespace: "\{{ request.object.metadata.name }}"
        name: "crb-admin-\{{ request.object.metadata.uid }}"
      name: create-cluster
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/Cluster
              operations:
                - CREATE